# PA Test Account
# ==================================
# https://test.authorize.net/ui/themes/anetcerttest/Logon.aspx
# Login: PlanetArgon1
# Password: Argon2010
# ==================================
# Payment gateway: 286776
# ==================================
# Current API Login ID:  7y4UnQPW5hd
# Current Transaction Key:  36F3Nak49u2B9kYN
# ==================================

# NOTE:
# If using a test Authorize.net account, remember to change the gateway setting in config.yml
# If using the PRODUCTION account in development or staging, you will also need to comment out
# the section for (ActiveMerchant::Billing::Base.gateway_mode) in development.rb/staging.rb

development:
  # NOTE: Bogus gateway will be used if test is set to true
  test: 'true'

  # Test Authorize.net account
  login: '7y4UnQPW5hd'
  password: '36F3Nak49u2B9kYN'

  # Production Authorize.net account
  #login: '2zSn67VN'
  #password: '4R74qSk8t4UZd8jZ'
staging:
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
  test: 'true'
production:
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
test:
  test: 'true'
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
test:
  test: 'true'
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
