# PA Test Account
# ==================================
# https://test.authorize.net/ui/themes/anetcerttest/Logon.aspx
# Login: PlanetArgon1
# Password: Argon2010
# ==================================
# Payment gateway: 286776
# ==================================
# Current API Login ID:  7y4UnQPW5hd
# Current Transaction Key:  78dy5J4mvF56Qwxs
# ==================================
# Note, if using a test Authorize.net account, remember to change the gateway setting in config.yml

development:
  login: '7y4UnQPW5hd'
  password: '78dy5J4mvF56Qwxs'
  test: 'false'
staging:
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
  test: 'true'
production:
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
test:
  test: 'true'
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
test:
  test: 'true'
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
