# PA Test ccount
# Current API Login ID:  3434tjLVAP5
# Current Transaction Key:  34vY3SvY4425sP53

development:
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
  test: 'true'
staging:
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
  test: 'true'
production:
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
test:
  test: 'true'
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
test:
  test: 'true'
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
