development:
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
  test: 'true'
staging:
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
  test: 'true'
production:
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
test:
  test: 'true'
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
test:
  test: 'true'
  login: '2zSn67VN'
  password: '4R74qSk8t4UZd8jZ'
