development:
  login: 'garyblessington'
  password: 'gpdb1970'
  api_key: '4ee0798c76cf6ec74c5db0abfa31efb2-us1'
  members_list_id: '97179e0605'
test:
  login: 'garyblessington'
  password: 'gpdb1970'
  api_key: '4ee0798c76cf6ec74c5db0abfa31efb2-us1'
  members_list_id: '97179e0605'
production:
  login: 'garyblessington'
  password: 'yoga2day'
  api_key: '2da81ad22b65db0e871de45fc639238d'
  members_list_id: 'e28cf19675'
